version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
    - FLASK_ENV=development  # This can be set to production
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - DB_DATABASE=flask_crud_db
    - DB_HOST=flask_db
    - DB_PORT=5432
    - DB_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=flask_crud_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: