version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_USERNAME=mike
      - DB_PASSWORD=your_password
      - DB_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@flask_db:5432/crud
#      - FLASK_ENV=development  # This can be set to production
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crud
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: