version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - IS_DOCKER=true  # Override to true for Docker environment
    depends_on:
      - flask_db
      - flask_mongo

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mike
    - POSTGRES_DB=flask_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  flask_mongo:
    container_name: flask_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  pgdata:
  mongodata: